### ISSUE TITLE
Add an eye-catching image

### ISSUE THREAD

**Issue by rienru** [danishi/dynamodb-csv#24]
@danishi 
**Describe alternatives you've considered**
This tool is great!

I can make illustrations, so I thought of an eye catch that would be perfect for this tool.
Please put it in README.md!

![DynamoDBCSV](https://user-images.githubusercontent.com/56535085/159007555-e72d1c26-eb44-46ca-bc38-c752164995bf.png)

If you like, make a PR.

**Comment by danishi** [comment]
@rienru 
Awesome!
Please do it!

**Comment by danishi** [comment]
![terminalizer](https://github.com/danishi/dynamodb-csv/assets/13270461/ec815dad-1ff6-4678-baa4-fd182ee35269)
