### ISSUE TITLE
Support configuration files in AWS CLI format

### ISSUE THREAD

**Issue by 2103Kuchinashi** [danishi/dynamodb-csv#46]
I think that it would be better to support configuration files in AWS CLI format and allow access to those in other directories, especially those under ~/.aws/.
It is tedious to create config.ini every time.

**Comment by danishi** [comment]
hi. @2103Kuchinashi 

That's exactly right.
I tried to be able to specify the AWS Profile.
This will be released soon.
If its helpful then im happy.
